#!/bin/bash
# claude-review.sh - PR review agent
# Usage: bash claude-review.sh --pr https://github.com/owner/repo/pull/123

set -euo pipefail

if [ $# -eq 0 ]; then
    echo "Usage: bash claude-review.sh --pr <PR_URL>"
    echo "   or: bash claude-review.sh --diff <PR_DIFF_FILE>"
    exit 1
fi

PR_URL=""
DIFF_FILE=""

while [ $# -gt 0 ]; do
    case "$1" in
        --pr) PR_URL="$2"; shift 2 ;;
        --diff) DIFF_FILE="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# Fetch diff from PR URL
if [ -n "$PR_URL" ]; then
    # Extract owner/repo/pr_number from URL
    PR_NUMBER=$(echo "$PR_URL" | grep -oP '/pull/\K\d+' || echo "")
    REPO_FULL=$(echo "$PR_URL" | grep -oP 'github\.com/\K[^/]+/[^/]+' || echo "")
    
    if [ -z "$PR_NUMBER" ] || [ -z "$REPO_FULL" ]; then
        echo "Error: Could not parse PR URL. Expected format: https://github.com/owner/repo/pull/123"
        exit 1
    fi
    
    DIFF_URL="https://github.com/$REPO_FULL/pull/$PR_NUMBER.diff"
    echo "Fetching diff from: $DIFF_URL"
    DIFF_CONTENT=$(curl -sL "$DIFF_URL")
    
    if [ -z "$DIFF_CONTENT" ]; then
        echo "Error: Could not fetch diff. Check the URL and try again."
        exit 1
    fi
elif [ -n "$DIFF_FILE" ]; then
    DIFF_CONTENT=$(cat "$DIFF_FILE")
else
    echo "Error: No PR URL or diff file provided."
    exit 1
fi

# Analyze the diff
echo "# PR Review Report"
echo ""
echo "## Summary"
echo ""

# Count changes
FILES_CHANGED=$(echo "$DIFF_CONTENT" | grep -c '^diff --git' || echo "0")
LINES_ADDED=$(echo "$DIFF_CONTENT" | grep -c '^+' || echo "0")
LINES_REMOVED=$(echo "$DIFF_CONTENT" | grep -c '^-' || echo "0")
LINES_ADDED=$((LINES_ADDED - $(echo "$DIFF_CONTENT" | grep -c '^+++' || echo "0")))
LINES_REMOVED=$((LINES_REMOVED - $(echo "$DIFF_CONTENT" | grep -c '^---' || echo "0")))

echo "This PR changes **$FILES_CHANGED files** with **+$LINES_ADDED / -$LINES_REMOVED lines**."
echo ""

# Extract changed files
echo "### Files Changed"
echo "$DIFF_CONTENT" | grep '^diff --git' | sed 's/diff --git a\/\(.*\) b\/.*/\1/' | while read -r f; do
    echo "- \`$f\`"
done
echo ""

# Check for potential risks
echo "## Identified Risks"
echo ""

RISK_FOUND=0

if echo "$DIFF_CONTENT" | grep -q '^+.*console\.log'; then
    echo "- ⚠️  **Debug code**: Contains \`console.log\` statements that should be removed before merge"
    RISK_FOUND=1
fi
if echo "$DIFF_CONTENT" | grep -q '^+.*TODO\|^+.*FIXME\|^+.*HACK'; then
    echo "- ⚠️  **Incomplete work**: Contains TODO/FIXME/HACK comments"
    RISK_FOUND=1
fi
if echo "$DIFF_CONTENT" | grep -q '^+.*apiKey\|^+.*password\|^+.*secret\|^+.*token'; then
    echo "- 🔴 **Security risk**: Potential secret/key exposure in diff"
    RISK_FOUND=1
fi
if echo "$DIFF_CONTENT" | grep -q '^+.*\.only('; then
    echo "- ⚠️  **Test risk**: Contains \`.only()\` in test files — will skip other tests"
    RISK_FOUND=1
fi
if echo "$DIFF_CONTENT" | grep -q '^+.*debugger'; then
    echo "- 🔴 **Debugger statement**: Contains \`debugger\` — will halt execution in dev tools"
    RISK_FOUND=1
fi
if echo "$DIFF_CONTENT" | grep -q '^+.*\bany\b' && echo "$DIFF_CONTENT" | grep -q '^+.*TypeScript'; then
    echo "- 🟡 **Type safety**: Uses \`any\` type — consider using stricter types"
    RISK_FOUND=1
fi

if [ "$RISK_FOUND" -eq 0 ]; then
    echo "No obvious risks detected in the diff."
fi
echo ""

# Improvement suggestions
echo "## Improvement Suggestions"
echo ""
echo "1. **Review for test coverage**: Ensure the changes include or update tests"
echo "2. **Check backward compatibility**: Verify the changes don't break existing API contracts"
echo "3. **Documentation**: Update any relevant docs if the public API changed"
echo "4. **Edge cases**: Consider empty states, error states, and boundary conditions"
echo ""

# Confidence score
echo "## Confidence Score"
echo ""
TOTAL_LINES=$((LINES_ADDED + LINES_REMOVED))
if [ "$TOTAL_LINES" -gt 500 ]; then
    echo "**Medium** — Large diff ($TOTAL_LINES lines), manual review recommended for complex logic"
elif [ "$TOTAL_LINES" -gt 100 ]; then
    echo "**High** — Moderate diff size, automated review is reliable for surface-level issues"
else
    echo "**High** — Small diff, automated review is reliable"
fi
echo ""
echo "---"
echo "*Generated by claude-review.sh — automated PR review tool*"
